name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-minimal  # Use minimal build to avoid memory issues
        env:
          # Use default values for CI/CD to avoid errors
          VITE_SUPABASE_URL: "https://example.supabase.co"
          VITE_SUPABASE_ANON_KEY: "example-key"
          VITE_GROQ_API_KEY: "gsk_example"
          VITE_BASE_PATH: "/"

      # Simple deployment step (placeholder)
      - name: Deploy to hosting
        run: |
          echo "Deploying to hosting service..."
          echo "This is a placeholder for actual deployment commands."
          echo "Deployment would normally push the ./dist directory to a hosting service."
          # Uncomment and configure when ready to deploy to a real service
          # Example for Netlify:
          # if [ -n "$NETLIFY_AUTH_TOKEN" ] && [ -n "$NETLIFY_SITE_ID" ]; then
          #   npx netlify-cli deploy --dir=./dist --prod
          # else
          #   echo "Skipping Netlify deployment - credentials not configured"
          # fi
        # Uncomment when ready to use actual deployment credentials
        # env:
        #   NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        #   NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
