name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run minimal build script
        run: node scripts/minimal-build.js

      # Simple deployment step (placeholder)
      - name: Create deployment report
        run: |
          mkdir -p reports
          echo "Deployment skipped for CI" > reports/deployment-report.txt

      - name: Skip deployment for now
        run: echo "Skipping deployment for CI"

      - name: Upload deployment report
        uses: actions/upload-artifact@v4
        with:
          name: deployment-report
          path: reports/
          retention-days: 5
